version: "3.8"

services:
  web:
    build:
      context: ./backend  # Changed from . to ./backend
      dockerfile: Dockerfile # Now it looks for Dockerfile inside the backend folder
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=vuln_app
    depends_on:
      - db
    labels:
      - traefik.docker.network=dokploy-network
      - traefik.enable=true
      - traefik.http.routers.vuln-web.rule=Host(`vuln-vuln-uxbk7m-af4399-151-247-197-185.traefik.me`)
      - traefik.http.routers.vuln-web.entrypoints=web
      - traefik.http.services.vuln-web.loadbalancer.server.port=3000
    networks:
      - dokploy-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=vuln_app
    volumes:
      - mysql_data:/var/lib/mysql
      # This stays as is because it's relative to the docker-compose.yml file
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dokploy-network

volumes:
  mysql_data:

networks:
  dokploy-network:
    external: true
